add cmake package
woboq/verdigris pull request #91
Opened 2022-05-11 03:14 UTC by dand-oss

From your cmake project
-----------------------

find_package(verdigris CONFIG REQUIRED)

target_link_libraries(${libname} PUBLIC
   ...
   verdigris::verdigris
   )

Todo
----
- build and run tests and benchmarks

Build result
------------

[0/1] Install the project...
-- Install configuration: "Release"
-- Up-to-date: INSTALLDIR/share/verdigris/cmake/verdigrisTargets.cmake
-- Up-to-date: INSTALLDIR/share/verdigris/cmake/verdigrisConfig.cmake
-- Up-to-date: INSTALLDIR/share/verdigris/cmake/verdigrisConfigVersion.cmake
-- Installing: INSTALLDIR/include/verdigris/wobjectcpp.h
-- Installing: INSTALLDIR/include/verdigris/wobjectdefs.h
-- Installing: INSTALLDIR/include/verdigris/wobjectimpl.h

2022-05-11 03:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/woboq/verdigris?pullRequest=91) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/woboq/verdigris?pullRequest=91) before we can accept your contribution.<br/><hr/>**Dan Dees** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/woboq/verdigris?pullRequest=91) it.</sub>

2022-05-11 08:10 UTC, ogoffart commented
I think the problem with the CLA assistant is that the email used in the git commit doesn't match the email registered in the GitHub account.

2022-08-07 23:07 UTC, arBmind requested changes
@dand-oss Thank you for your PR.

Would it be possible/necessary to also express that Verdigris also requires a Qt5 or Qt6 to work as intended?

2022-08-07 23:07 UTC, arBmind commented on CMakeLists.txt
> +target_compile_features(${libname} INTERFACE cxx_std_11)
I'd guess we need C++14 here.

2023-01-01 21:57 UTC, arBmind commented
Please note: #99 adds full CMake support to Verdigris. That contains install package building and running all test targets.

2024-07-29 23:32 UTC, closed without merging